config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "up" => "rails/health#show", as: :rails_health_check

  resources :features do
    collection do
      post :index
    end

    resources :comments, only: [:create, :destroy, :edit, :update] do
      resources :comments, only: [:create], as: 'replies'
    end
    resources :votes, only: [:create]
  end

  root 'features#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  broadcasts_refreshes_to :feature

  belongs_to :user
  belongs_to :feature

  belongs_to :parent, class_name: "Comment", optional: true
  has_many :replies, class_name: "Comment", foreign_key: :parent_id, dependent: :destroy

  validates :content, presence: true

  MAX_NESTING_LEVEL = 1

  def nesting_level
    parent ? parent.nesting_level + 1 : 0
  end
end

app/models/feature.rb
class Feature < ApplicationRecord
  belongs_to :user
  has_many :votes, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :voters, through: :votes, source: :user

  enum status: { open: 0, in_progress: 1, done: 2}

  def self.status_options
    [['Oldest', 'old'], ['Newest', 'new']] + statuses.keys.map { |key| [key.to_s.humanize.titleize, key] }
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_person_name

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :features
  has_many :votes
  has_many :comments
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :feature

  validates :user_id, uniqueness: { scope: :feature_id }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_feature
  before_action :set_comment, only: [:edit, :update, :destroy]

  def create
    @comment = @feature.comments.build(comment_params.merge(user: current_user))
    @nesting_level = @comment.parent ? 1 : 0

    if @comment.save
      flash.now[:notice] = "Comment was successfully created"
      respond_to do |format|
        format.html { redirect_to @feature }
      end
    else
      flash.now[:alert] = "Failed to add comment"
      respond_to do |format|
        format.html { redirect_to @feature }
      end
    end
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      respond_to do |format|
        format.html { redirect_to @feature, notice: "Comment was successfully updated." }
      end
    else
      respond_to do |format|
        format.html { redirect_to @feature, alert: "Failed to update comment." }
      end
    end
  end

  def destroy
    @comment.destroy
    flash.now[:notice] = "Comment was successfully deleted"
    respond_to do |format|
      format.html { redirect_to @feature }
    end
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def set_feature
    @feature = Feature.find(params[:feature_id])
  end

  def comment_params
    params.require(:comment).permit(:content, :parent_id)
  end
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_feature, only: %i[ show edit update destroy ]

  def index
    @status_filter = params[:status_filter] || 'all'
    @search_query = params[:search]
    @pagy, @features = pagy(FeatureFilter.new(Feature.where(nil), @status_filter, @search_query).filtered_features)

    @feature = Feature.new

    respond_to do |format|
      format.turbo_stream
      format.html
    end
  end

  def show
    @comment = Comment.new
    @comments = @feature.comments.where(parent_id: nil)
  end

  def new
    @feature = Feature.new
  end

  def edit
  end

  def create
    @feature = Feature.new(feature_params.merge(user: current_user))

    respond_to do |format|
      if @feature.save
        format.html { redirect_to features_path, notice: "Feature was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @feature.update(feature_params)
        format.html { redirect_to feature_url(@feature), notice: "Feature was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @feature.destroy!

    respond_to do |format|
      format.html { redirect_to features_path, notice: "Feature was successfully destroyed." }
    end
  end

  private
    def set_feature
      @feature = Feature.find(params[:id])
    end

    def feature_params
      params.require(:feature).permit(:title, :description, :status)
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_feature

  def create
    @vote = @feature.votes.new(user: current_user)

    respond_to do |format|
      if @vote.save
        flash.now[:notice] = "Vote casted successfully"
        format.html { redirect_to @feature }
        format.turbo_stream
      else
        flash.now[:alert] = "You have already voted for this feature"
        format.html { redirect_to @feature }
        format.turbo_stream
      end
    end
  end

  private

  def set_feature
    @feature = Feature.find(params[:feature_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def user_avatar_with_name(user)
    content_tag :div, class: "flex items-center gap-3" do
      avatar = content_tag(:div, class: "rounded-full size-6 text-xs flex items-center justify-center font-semibold #{['bg-red-100', 'bg-blue-100', 'bg-green-100', 'bg-pink-100', 'bg-purple-100'].sample}") do
        user.first_name.first.upcase
      end

      name = content_tag(:p, user.name, class: "font-medium text-sm")

      avatar + name
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/features_helper.rb
module FeaturesHelper
  def feature_status(feature)
    base_classes = "text-xs rounded-sm px-1 py-px"
    case feature.status
    when 'in_progress'
      content_tag :span, "In Progress", class: "bg-orange-300/40 text-orange-700 #{base_classes}"
    when 'open'
      content_tag :span, "Open", class: "bg-green-300/40 text-green-700 #{base_classes}"
    when 'done'
      content_tag :span, "Done", class: "bg-gray-300/40 text-gray-700 #{base_classes}"
    end
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_comment.html.erb
<div class="py-4" id="<%= dom_id(comment)%>_container">
  <div class="flex items-start gap-4">
    <div class="rounded-full size-8 text-sm flex items-center justify-center font-semibold <%= ["bg-red-100", "bg-blue-100", "bg-green-100", "bg-pink-100", "bg-purple-100"].sample %>">
      <%= comment.user.first_name.first.upcase %>
    </div>

    <div class="flex-1 pt-1">
      <p class="font-semibold"><%= comment.user.name %></p>

      <%= turbo_frame_tag dom_id(comment) do %>
        <div class="prose mt-1 mb-3">
          <%= simple_format comment.content %>
        </div>

        <% if comment.persisted? && comment.user == current_user %>
          <%= link_to "Edit", edit_feature_comment_path(comment.feature, comment), class: "underline font-medium" %>
        <% end %>
      <% end %>

      <% if comment.persisted? && comment.user == current_user %>
        <%= button_to "Delete", feature_comment_path(comment.feature, comment), method: :delete, class: "underline font-medium mb-6" %>
      <% end %>

      <!-- Reply Form -->
      <% if comment.nesting_level < Comment::MAX_NESTING_LEVEL %>
        <div data-controller="toggle">
          <button class="btn btn-white btn-sm" data-toggle-target="btn" data-action="click->toggle#toggle">Reply</button>
          <div class="hidden" data-toggle-target="toggleable">
            <%= render "comments/reply_form", feature: comment.feature, comment: comment %>
          </div>
        </div>
      <% end %>

      <!-- Render replies recursively -->
      <div class="pl-4 mt-3 border-l border-dashed border-gray-300">
        <%= render partial: 'comments/comment', collection: comment.replies, as: :comment, locals: { nesting_level: 1 }  %>
      </div>
    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_with model: [feature, comment] do |f| %>
  <div class="mb-3">
    <%= f.label :content, "Reply", class: "sr-only" %>
    <%= f.text_area :content, class: "form-input", placeholder: "Type a response" %>
  </div>

  <% if f.object.errors.any? %>
    <div class="text-red-500 pb-3 text-sm">
      <ul>
        <% f.object.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/comments/_reply_form.html.erb
<div class="my-2">
  <%= form_with(model: [feature, Comment.new]) do |f| %>

    <div class="mb-3">
      <%= f.label :content, "Reply", class: "sr-only" %>
      <%= f.text_area :content, class: "form-input", placeholder: "Type your response to #{comment.user.name.first}" %>
    </div>

    <%= f.hidden_field :parent_id, value: comment.id %>

    <% if comment.errors.any? %>
      <div class="text-red-500 pb-3 text-sm">
        <ul>
          <% comment.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.submit "Reply", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/comments/edit.html.erb
<%= turbo_frame_tag dom_id(@comment) do %>
  <%= render "comments/form", feature: @comment.feature, comment: @comment %>
<% end %>

app/views/features/_feature.html.erb
<div id="<%= dom_id feature %>" class="p-4 hover:bg-slate-50 flex items-start gap-6">
  <%= link_to feature, class: "flex-1", target: :_top do %>
    <h3 class="font-semibold tracking-tight"><%= feature.title %></h3>
    <div class="prose mb-3">
      <%= simple_format truncate(feature.description, length: 100) %>
    </div>

    <div class="flex items-center gap-2">
      <div class="flex items-center gap-1.5 text-xs text-gray-600">
        <%= inline_svg_tag "chat-bubble-oval-left.svg", class: "size-4 stroke-current text-gray-600" %>
        <span><%= feature.comments.size %></span>
      </div>
      <div class="text-[8px] text-gray-500">
        &bull;
      </div>
      <div class="-top-px relative">
        <%= feature_status(feature) %>
      </div>
    </div>

  <% end %>
  <%= render "votes/vote_button", feature: feature %>
</div>

app/views/features/_features.html.erb
<%= turbo_frame_tag "features" do %>
  <div class="border-x border-b rounded-b divide-y">
    <%= render @features %>
  </div>
<% end %>

app/views/features/_form.html.erb
<%= form_with(model: feature) do |form| %>
  <div class="p-4">
    <%= render "shared/error_messages", resource: form.object %>

    <div class="mb-3">
      <%= form.label :title, class: "sr-only" %>
      <%= form.text_field :title, class: "appearance-none text-base font-normal py-2 block w-full rounded-md focus:ring-none focus:shadow-none focus:border-none focus:outline-none", placeholder: "Short, descriptive title", autofocus: true %>
    </div>

    <div class="mb-3">
      <%= form.label :description, class: "form-label mb-0" %>
      <%= form.text_area :description, class: "appearance-none text-base font-normal py-2 block w-full rounded-md focus:ring-none focus:shadow-none focus:border-none focus:outline-none", placeholder: "Any additional details" %>
    </div>
  </div>

  <div class="flex items-center gap-6 justify-end w-full bg-slate-50 border-t p-3">
    <%= form.submit "Create post", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/features/edit.html.erb
<h1>Editing feature</h1>

<%= render "form", feature: @feature %>

<br>

<div>
  <%= link_to "Show this feature", @feature %> |
  <%= link_to "Back to features", features_path %>
</div>

app/views/features/index.html.erb
<div class="max-w-5xl rounded mx-auto px-4 mt-10">
  <div class="grid grid-cols-1 md:grid-cols-12 bg-white">
    <aside class="md:col-span-3 md:p-6">
      <h3 class="font-semibold text-xs uppercase mb-3">Category</h3>

      <ul class="-mx-3 space-y-2">
        <li>
          <%= link_to "Products", "#", class: "px-3 py-1 rounded-md hover:bg-slate-50 block" %>
        </li>
        <li>
          <%= link_to "Features", "#", class: "px-3 py-1 rounded-md hover:bg-slate-50 block" %>
        </li>
        <li>
          <%= link_to "Bugs", "#", class: "px-3 py-1 rounded-md hover:bg-slate-50 block" %>
        </li>
        <li>
          <%= link_to "Other", "#", class: "px-3 py-1 rounded-md hover:bg-slate-50 block" %>
        </li>
      </ul>
    </aside>

    <div class="md:col-span-9 md:px-8 md:pt-8 md:pb-32">
      <h1 class="font-bold text-xl tracking-tight text-slate-800 mb-3 capitalize"><%= pluralize(Feature.all.size, 'feature') %></h1>

      <div class="rounded border mb-6">
        <%= render "features/form", feature: @feature %>
      </div>

      <div class="flex items-center gap-6 justify-between w-full bg-slate-50 rounded-t border p-4">
        <%= form_with url: features_path, method: :post, class: "flex items-center gap-4 justify-between w-full", data: { turbo_frame: "features", controller: "filter" } do %>
          <div class="flex items-center gap-4">
            Showing
            <%= select_tag :status_filter, options_for_select(Feature.status_options, @status_filter), class: "form-select w-full", data: { action: "change->filter#submitForm" } %>
            posts
          </div>

          <div>
            <label for="search" class="sr-only">Search</label>
            <%= search_field_tag :search, params[:search], id: "feature_search", class: "form-input w-full", placeholder: "Search...", data: { action: "input->filter#submitForm" } %>
          </div>
        <% end %>
      </div>

      <%= turbo_frame_tag "features" do %>
        <div class="border-x border-b rounded-b divide-y">
          <%= render @features %>
        </div>
      <% end %>

      <%== pagy_nav(@pagy) if @pagy.pages > 1 %>

    </div>
  </div>
</div>

app/views/features/index.turbo_stream.erb
<%= turbo_stream.update "features" do %>
  <div class="border-x border-b rounded-b divide-y">
    <%= render @features %>
  </div>
<% end %>

app/views/features/new.html.erb
<h1>New feature</h1>

<%= render "form", feature: @feature %>

app/views/features/show.html.erb
<div class="max-w-5xl rounded mx-auto px-4 mt-10">
  <div class="grid grid-cols-1 md:grid-cols-12 bg-white">
    <aside class="md:col-span-3 md:p-6">
      <h3 class="font-semibold text-xs uppercase mb-3 -mx-3">Voters</h3>

      <ul class="-mx-3 space-y-3">
        <% @feature.voters.each do |voter| %>
          <%= user_avatar_with_name(voter) %>
        <% end %>
      </ul>
    </aside>

    <div class="md:col-span-9 md:p-8">

      <div class="flex items-center gap-6 mb-6">
        <%= render "votes/vote_button", feature: @feature %>

        <div class="flex-1">
          <h1 class="text-2xl font-semibold tracking-tight"><%= @feature.title %></h1>
          <%= feature_status(@feature) %>
        </div>
      </div>

      <div class="my-2">
        <%= user_avatar_with_name(@feature.user) %>
      </div>

      <div class="prose mb-16">
        <%= simple_format @feature.description %>
      </div>

      <%# Comments %>
      <div class="mb-6">
        <%= render "comments/form", feature: @feature, comment: Comment.new %>
      </div>

      <h3 class="font-normal text-gray-500">Activity feed</h3>

      <%= turbo_stream_from @feature %>

      <%= render @comments %>

    </div>
  </div>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full">
  <head>
    <title>Hanny</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>

    <%= turbo_refreshes_with method: :morph, scroll: :preserve %>
    <%= yield :head %>
  </head>

  <body class="bg-white text-slate-800 antialiased min-h-screen h-full accent-sky-500">
    <%= turbo_frame_tag "flash" %>
    <%= render "shared/nav" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div class="bg-rose-50 text-rose-700 sm:px-9 sm:py-6 px-6 py-6 rounded-lg mb-6 dark:bg-rose-400/10 dark:border dark:border-rose-400/20 dark:text-rose-50 text-sm" role="alert">
    <p class="font-bold"><%= pluralize(resource.errors.count, "error") %> prohibited this post from being saved:</p>
    <ul class="list-disc mt-3 ml-4">
      <% resource.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <div data-controller="flash" data-flash-target="toast" class="fixed z-50 top-2 right-2 border rounded-md p-3 shadow-lg opacity-100 translate-x-full transition-transform ease-in-out duration-300 transform <%= type == :alert ? "bg-red-50 border-red-500/50 text-red-800" : "bg-white border-gray-300/90 text-gray-800" %>">
    <div class="flex items-center justify-between gap-4">
      <span><%= message %></span>
      <button type="button" data-action="click->flash#dismiss" class="p-1 hover:bg-gray-100/70 flex items-center justify-center rounded-md">
        <%= inline_svg_tag "x-mark.svg", class: "size-4 stroke-current text-gray-600 pointer-events-none" %>
      </button>
    </div>
  </div>
<% end %>

app/views/shared/_links.html.erb
<% if user_signed_in? %>
  <div class="flex gap-6 items-center">
    <p class="text-sm"><%= current_user.email %></p>
    <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "underline text-sky-500 hover:text-sky-600 font-medium" %>
  </div>
<% else %>
  <%= link_to "Sign in", new_user_session_path, class: "underline text-sky-500 hover:text-sky-600 font-medium" %>
<% end %>

app/views/shared/_logo.html.erb
<%= link_to root_path, class: "flex items-center justify-center gap-2 p-3 hover:bg-slate-50 rounded-t-md" do %>
  <svg class="stroke-current size-6 text-sky-600" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><title>arrow-up-circle</title><g fill="none"><path d="M15 11.25l-3-3m0 0l-3 3m3-3v7.5M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0z" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path></g></svg>
  <span class="font-bold tracking-tight text-slate-950 text-xl">Hanny</span>
<% end %>

app/views/shared/_nav.html.erb
<div class="bg-white py-1.5 px-4 shadow-sm mb-6">
  <div class="max-w-6xl mx-auto flex justify-between items-center">
    <%= render "shared/logo" %>
    <%= render "shared/links" %>
  </div>
</div>

app/views/votes/_vote_button.html.erb
<%= turbo_frame_tag "#{dom_id(feature)}_vote_button" do %>
  <% unless feature.votes.exists?(user: current_user) %>
    <%= button_to feature_votes_path(feature), class: "btn btn-white !flex-col" do %>
      <%= inline_svg_tag "arrow-up.svg", class: "size-3 stroke-current" %>
      <span><%= feature.votes.size %></span>
    <% end %>
  <% else %>
    <button class="btn btn-white !flex-col  disabled:opacity-70 disabled:pointer-events-none disabled:bg-gray-100 disabled:shadow-none" disabled>
      <%= inline_svg_tag "arrow-up.svg", class: "size-3 stroke-current" %>
      <span><%= feature.votes.size %></span>
    </button>
  <% end %>
<% end %>

app/views/votes/create.turbo_stream.erb
<%= turbo_stream.update "flash", partial: "shared/flash" %>

<%= turbo_stream.update "#{dom_id(@feature)}_vote_button" do %>
  <%= render "votes/vote_button", feature: @feature %>
<% end %>